### ISSUE TITLE
Padding/margins of structures

### ISSUE THREAD

**Issue by filipsPL** [kienerj/molecule-slide-generator#5]
It would be awesome to have the option to specify the padding (or margins) of structures:

![obraz](https://user-images.githubusercontent.com/11406606/124726285-e6855a00-df0d-11eb-81b6-c02a951c483d.png)

 Sometimes the image is too crowded to be readable.

**Comment by kienerj** [comment]
First of it's pure coincidence I'm replying this quickly, don't get used to it!

**For my own reference:**

 check drawOptions -> `padding` option and `additionalAtomLabelPadding` while `padding` is 

> fraction of empty space to leave around the molecule with default = 0.05

and `additionalAtomLabelPadding` 

> additional padding to leave around atom labels. Expressed as a fraction of the font size with default 0

**As a reply to you:** 

If the image is too crowded simply reduce the amount of molecules on the Image/slide or increase the slide dimension. See constructor named arguments. This usually requires some trial/error to get a nice looking result.

From experience if you have very different types of molecules like long chains plus bulky molecules on the same slide, it's harder or impossible to create a very nice looking result.

The molecules have a fixed maximum size defined by `bond_length` argument. If a molecule is too big to fit, it will shrink but that doesn't wok perfectly with atom labels. hence I advice to only use similar sized molecules per slide.  But main point is, molecules won't grow beyond `bond_length` and hence more space per molecule = more padding.

**Comment by filipsPL** [comment]
Great, thanks for (not usual) quick reply.
